<<<<<<< HEAD
enableElasticMaster: true
enableElasticData: true
enableElasticExporter: true
enableMongoDb: true
enablePostgreSql: true
enableMariaDB: true

elastic-master:
  nodeGroup: "master"
  replicas: 1
  minimumMasterNodes: -1
  antiAffinity: "soft"
  roles:
    master: "true"
    ingest: "false"
    data: "false"
    remote_cluster_client: "false"
    ml: "false"
  resources:
    requests:
      cpu: "1000m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"

elastic-data:
  nodeGroup: "data"
  masterService: "elasticsearch-master"
  replicas: 3
  antiAffinity: "soft"
  roles:
    master: "false"
    ingest: "true"
    data: "true"
    remote_cluster_client: "true"
    ml: "true"
  resources:
    requests:
      cpu: "1000m"
      memory: "768Mi"
    limits:
      cpu: "1000m"
      memory: "768Mi"

prometheus-elasticsearch-exporter:
  serviceMonitor: 
    enabled: true
  es:
    uri: http://elasticsearch-master.{{ .Release.Namespace }}:9200
    timeout: 120s

mongodb:
  resources:
    requests:
      cpu: "1000m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"
  architecture: replicaset
  replicaCount: 3
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

postgresql:
  primary:
    requests:
      cpu: "1000m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"
  auth:
    database: "postgresql"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

mariadb:
  # The architecture can be `standalone` or `replication`, in this case, we'll use replication since we need 2 replicas.
  architecture: replication
  primary:
    # Limit the computer resources that the primary will get
    resources:
      requests:
        cpu: "1000m"
        memory: "256Mi"
      limits:
        cpu: "1000m"
        memory: "256Mi"
  secondary:  
    # Define the amount of replicas we'll have
    replicaCount: 2

    # Limit the computer resources that the secondary will get
    resources:
      requests:
        cpu: "1000m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "512Mi"
  
  # We need metrics enabled to enable the serviceMonitor
  metrics: 
    enabled: true

    # The service monitor enables us to work with prometheus
    serviceMonitor: 
      enabled: true
