apiVersion: v2
name: monitoring
description: Herramientas de observabilidad de la tarea corta 1 | Base de Datos II
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: kube-prometheus
    version: "8.1.2"
    repository: https://charts.bitnami.com/bitnami
    condition: enablePrometheus
  - name: grafana
    version: "8.2.2"
    repository: https://charts.bitnami.com/bitnami
    condition: enableGrafana